// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keegfbthstdxjyqxykya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlZWdmYnRoc3RkeGp5cXh5a3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTc3OTUsImV4cCI6MjA2ODU5Mzc5NX0.mcAAK4_0epqv5_1pi3rXVpGM9UXfkaG2jVd5gHW6Y7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});